name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin

    - name: Install Citizens to Local Maven Repo
      run: mvn install:install-file -Dfile=libs/citizens-2.0.16.jar -DgroupId=net.citizensnpcs -DartifactId=citizens -Dversion=2.0.16 -Dpackaging=jar

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Rename JAR
      run: |
        mkdir build
        mv target/*.jar build/MayorElection.jar

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MayorElection
        path: build/MayorElection.jar

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/MayorElection.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
